# Generated by Django 3.2.16 on 2023-01-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='quiz_topic',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('qno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('marks', models.IntegerField(default=5)),
                ('difficulty_level', models.CharField(max_length=10)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.quiz_topic')),
            ],
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('qno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='home.questions')),
            ],
        ),
    ]
